[bar]
order = [ "default" ]

    [bar.default]
    attach_panels = true
    background_opacity = 0.75
    capsule = false
    capsule_border = "primary"
    capsule_opacity = 0.14999999105930328
    center = [ "cpu", "ram", "temp", "sysmon" ]
    color = "primary"
    contact_shadow = false
    end = [ "screen_recorder", "notifications", "clipboard", "bluetooth", "volume", "brightness", "session" ]
    margin_ends = 10
    margin_h = 5
    margin_v = 5
    padding = 10
    position = "left"
    reserve_space = true
    start = [ "control-center", "launcher", "bongocat", "media", "workspaces", "tray" ]
    thickness = 25
    widget_spacing = 10

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 10

[battery.device."/org/freedesktop/UPower/devices/headphones_dev_AC_BF_71_DD_05_5C"]
warning_threshold = 20

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

[control_center]
compact = false

[desktop_widgets]
schema_version = 1
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    cx = 1710.0
    cy = 990.739990234375
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.3510638475418091
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    cx = 1616.0
    cy = 540.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.9999998807907104
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        aspect_ratio = 2.5
        background = false
        bands = 32
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    cx = 1430.4000244140625
    cy = 990.239990234375
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.8400000333786011
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    cx = 1686.7333984375
    cy = 112.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.2666666507720947
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = false
        layout = "horizontal"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    cx = 1754.0
    cy = 370.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = false

[dock]
auto_hide = true
position = "right"
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = false
    lock_before_suspend = true
    timeout = 900

[location]
address = "Jayanagar,Bengaluru,India"

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    cx = 980.0
    cy = 540.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    cx = 1710.0
    cy = 990.739990234375
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.3510638475418091
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    cx = 1616.0
    cy = 540.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.9999998807907104
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        aspect_ratio = 2.5
        background = false
        bands = 32
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    cx = 1430.4000244140625
    cy = 990.239990234375
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.8400000333786011
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    cx = 1686.7333984375
    cy = 112.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.2666666507720947
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        layout = "horizontal"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    cx = 1754.0
    cy = 370.0
    output = "HDMI-A-1"
    rotation = 0.0
    scale = 1.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false


[noctalia_state]
setup_wizard_completed = true

[notification]
background_opacity = 0.5
layer = "overlay"
position = "top_center"

[osd]
background_opacity = 0.5
offset_y = 5.0
position = "top_center"

[shell]
avatar_path = "me.jpg"
font_family = "Jetbrains Mono"
lang = "en"
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
time_format = "{:%H:%M:%S}"

    [shell.panel]
    clipboard_placement = "attached"
    control_center_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_wallpaper = true
    session_placement = "centered"
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 32

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = true
    shortcut = "3"
    variant = "default"

[system.monitor]
cpu_poll_seconds = 1
disk_poll_seconds = 5
gpu_poll_seconds = 1
memory_poll_seconds = 1

[theme]
builtin = "Rosé Pine"
community_palette = "Catppuccin Lavender"
custom_palette = "Catppuccin Macchiato"
source = "custom"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "kitty" ]

[wallpaper]
directory = "/home/darshan/wallpapers"
transition = [ "honeycomb", "stripes" ]

    [wallpaper.default]
    path = "/home/darshan/wallpapers/20.jpg"

    [wallpaper.last]
    path = "/home/darshan/wallpapers/20.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/darshan/wallpapers/20.jpg"

[weather]
address = "Bengaluru,India"
refresh_minutes = 5

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.cpu]
display = "gauge"

[widget.launcher]
color = "primary"
glyph = "heart"
use_distro_logo = true

[widget.network]
show_label = false

[widget.ram]
display = "text"
show_label = false
stat = "ram_pct"

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"

[widget.sysmon]
display = "gauge"
stat = "disk_pct"

[widget.taskbar]
inactive_opacity = 0.75
only_active_workspace = true

[widget.temp]
display = "gauge"
show_label = false

[widget.workspaces]
capsule = false
color = "primary"
display = "id"
occupied_color = "#EEBBAA"
